# Generated by Django 4.2 on 2026-05-16 01:53

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('wechat', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=core.models.generate_order_number, max_length=20, unique=True, verbose_name='订单编号')),
                ('shoot_date', models.DateField(verbose_name='拍摄日期')),
                ('shoot_time', models.TimeField(verbose_name='拍摄时间')),
                ('location', models.CharField(max_length=200, verbose_name='拍摄地点')),
                ('status', models.CharField(choices=[('pending', '待拍摄'), ('shooting', '拍摄中'), ('selected', '已选片'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='订单状态')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='定金')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '拍摄订单',
                'verbose_name_plural': '拍摄订单',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套餐名称')),
                ('description', models.TextField(verbose_name='套餐描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('days', models.IntegerField(verbose_name='拍摄天数')),
                ('photos_count', models.IntegerField(verbose_name='精修照片数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '套餐',
                'verbose_name_plural': '套餐',
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='摄影师姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('level', models.CharField(max_length=50, verbose_name='级别')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '摄影师',
                'verbose_name_plural': '摄影师',
                'db_table': 'photographer',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='尾款金额')),
                ('payment_method', models.CharField(max_length=50, verbose_name='支付方式')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='支付时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '尾款结算',
                'verbose_name_plural': '尾款结算',
                'db_table': 'settlement',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package', verbose_name='套餐'),
        ),
        migrations.AddField(
            model_name='order',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.photographer', verbose_name='摄影师'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='预约日期')),
                ('appointment_time', models.TimeField(verbose_name='预约时间')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='客户')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.package', verbose_name='套餐')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.photographer', verbose_name='摄影师')),
            ],
            options={
                'verbose_name': '客户预约',
                'verbose_name_plural': '客户预约',
                'db_table': 'appointment',
            },
        ),
    ]
