export const mockDeviceList = [
  { id: 1, deviceCode: 'EDU-001', servicePoint: '市政务服务中心', location: '一楼大厅A区', status: '正常' },
  { id: 2, deviceCode: 'EDU-002', servicePoint: '市政务服务中心', location: '一楼大厅B区', status: '故障' },
  { id: 3, deviceCode: 'EDU-003', servicePoint: '区政务服务中心', location: '二楼服务窗口', status: '离线' },
  { id: 4, deviceCode: 'EDU-004', servicePoint: '区政务服务中心', location: '三楼自助服务区', status: '正常' },
  { id: 5, deviceCode: 'EDU-005', servicePoint: '街道便民服务中心', location: '入口处', status: '维护中' },
  { id: 6, deviceCode: 'EDU-006', servicePoint: '街道便民服务中心', location: '办事大厅', status: '正常' },
  { id: 7, deviceCode: 'EDU-007', servicePoint: '镇政务服务中心', location: '一楼大厅', status: '故障' },
  { id: 8, deviceCode: 'EDU-008', servicePoint: '镇政务服务中心', location: '二楼', status: '正常' },
  { id: 9, deviceCode: 'EDU-009', servicePoint: '开发区政务服务中心', location: 'A栋一楼', status: '离线' },
  { id: 10, deviceCode: 'EDU-010', servicePoint: '开发区政务服务中心', location: 'B栋二楼', status: '正常' },
  { id: 11, deviceCode: 'EDU-011', servicePoint: '高新区政务服务中心', location: '主楼大厅', status: '正常' },
  { id: 12, deviceCode: 'EDU-012', servicePoint: '高新区政务服务中心', location: '副楼一楼', status: '故障' },
  { id: 13, deviceCode: 'EDU-013', servicePoint: '新区政务服务中心', location: '服务大厅A区', status: '正常' },
  { id: 14, deviceCode: 'EDU-014', servicePoint: '新区政务服务中心', location: '服务大厅B区', status: '维护中' },
  { id: 15, deviceCode: 'EDU-015', servicePoint: '园区政务服务中心', location: '一号楼大厅', status: '正常' },
  { id: 16, deviceCode: 'EDU-016', servicePoint: '园区政务服务中心', location: '二号楼入口', status: '离线' },
  { id: 17, deviceCode: 'EDU-017', servicePoint: '东区政务服务中心', location: '一楼自助区', status: '正常' },
  { id: 18, deviceCode: 'EDU-018', servicePoint: '东区政务服务中心', location: '二楼办事区', status: '故障' },
  { id: 19, deviceCode: 'EDU-019', servicePoint: '西区政务服务中心', location: '大厅入口处', status: '正常' },
  { id: 20, deviceCode: 'EDU-020', servicePoint: '西区政务服务中心', location: '二楼南侧', status: '正常' },
  { id: 21, deviceCode: 'EDU-021', servicePoint: '南区政务服务中心', location: '一楼大厅', status: '维护中' },
  { id: 22, deviceCode: 'EDU-022', servicePoint: '南区政务服务中心', location: '三楼', status: '正常' },
  { id: 23, deviceCode: 'EDU-023', servicePoint: '北区政务服务中心', location: 'A区服务台旁', status: '离线' },
  { id: 24, deviceCode: 'EDU-024', servicePoint: '北区政务服务中心', location: 'B区自助区', status: '正常' },
  { id: 25, deviceCode: 'EDU-025', servicePoint: '中心区政务服务中心', location: '主楼一楼', status: '故障' }
]
