# Generated by Django 4.2 on 2026-05-15 17:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('model', models.CharField(max_length=50, verbose_name='型号')),
                ('car_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='车型')),
                ('color', models.CharField(max_length=30, verbose_name='颜色')),
                ('seats', models.IntegerField(verbose_name='座位数')),
                ('daily_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='日租金')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=5, verbose_name='超时费率')),
                ('status', models.CharField(choices=[('available', '可租用'), ('rented', '已出租'), ('maintenance', '维修中')], default='available', max_length=20, verbose_name='状态')),
                ('image', models.URLField(blank=True, null=True, verbose_name='车辆图片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆管理',
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('driver_license', models.CharField(max_length=20, unique=True, verbose_name='驾驶证号')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='订单编号')),
                ('start_date', models.DateField(verbose_name='取车日期')),
                ('end_date', models.DateField(verbose_name='还车日期')),
                ('pickup_location', models.CharField(max_length=100, verbose_name='取车地点')),
                ('return_location', models.CharField(max_length=100, verbose_name='还车地点')),
                ('rental_days', models.IntegerField(verbose_name='租赁天数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预计总金额')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='押金')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='实际取车时间')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='实际还车时间')),
                ('actual_rental_days', models.IntegerField(blank=True, null=True, verbose_name='实际租赁天数')),
                ('overtime_days', models.IntegerField(default=0, verbose_name='超时天数')),
                ('base_rental', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='基础租金')),
                ('overtime_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='超时费用')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际结算金额')),
                ('status', models.CharField(choices=[('pending', '待取车'), ('picked_up', '已取车'), ('returned', '已还车'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car', verbose_name='车辆')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
    ]
